DROP TABLE IF EXISTS notices; DROP TABLE IF EXISTS usersandpasswords;

Queries: CREATE TABLE usersandpasswords ( user_id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50) NOT NULL UNIQUE, password VARCHAR(100) NOT NULL, role VARCHAR(20) NOT NULL, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, email VARCHAR(100) NOT NULL UNIQUE, student_id VARCHAR(20), major VARCHAR(100), year VARCHAR(20) );

CREATE TABLE notices ( notice_id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(100) NOT NULL, message TEXT NOT NULL, category VARCHAR(50) NOT NULL, priority VARCHAR(20) NOT NULL, year_level VARCHAR(30) NOT NULL, created_by INT NOT NULL, deadline_date DATE NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,